### ISSUE TITLE
exp and sum tensorflow tests

### ISSUE THREAD

**Issue by mauinz** [charanpald/tyre-hug#1]
Hi, first of all, thanks for running the basic linear algebra tests for the common tensor libraries!

I noticed the code linalg.py file you run tensorflow.exp() twice, should one of these be sum()? I could be missing a point here, apologies if that's the case.

https://github.com/charanpald/tyre-hug/blob/master/tyrehug/exp/linalg.py#L134
https://github.com/charanpald/tyre-hug/blob/master/tyrehug/exp/linalg.py#L140

**Comment by charanpald** [comment]
Hi mauinz, you are absolutely correct - the 2nd exp should in fact be a sum to be inline with the other benchmarks. I realise I'd been a little careless with this code - I'll update this and the blog post. Thanks for raising this issue!
